### PR TITLE
Panels and Components use `ratio`

### PR DESCRIPTION
**Pull request by jsundra**
The README mentions panels using `ratio`, but it actually isn't referrenced in the codebase at all past its default params setting in Panel.

With this PR, not specifying a ratio uses the default to what the js values default to (the 60/40 split mentioned throughout the code, not the 70/30 from the README). When a panel specifies a ratio, that is used for all components under that panel. Components themselves can specify their own ratio as an override. This can be useful for things like a checkbox where more of a label can be seen, since an entire 60% width for just a little checkbox goes to waste.

I purposefully didn't touch the README or change the defaults in js away from 60/40. Not sure what the split should be, so leaving it as it.

### CODE REVIEW

**Comment by jsundra** [comment]
Closing -- repo is long since dead and I'm sick of it polluting my PR list.

**Comment by automat** [comment]
@jsundra The tone of your comment is completely unnecessary.

**Comment by jsundra** [comment]
Hahahaha seriously? You ignore all PRs and issues and don't touch this repo for years, but get offended when the people trying to help give up?

If you leave a repo for dead, don't come back randomly to just troll comments.

**Comment by automat** [comment]
I have zero obligations to do anything here. You are the one leaving these type of comments and start trolling. Good luck with this kind of attitude.

**Comment by jsundra** [comment]
It's very clear that you're putting in no effort in this repo. Which is perfectly fine, it happens. Just shocked to see you care so much about a project you also seem to care so little about. Just make up your mind?

**Comment by automat** [comment]
This project is six years old. You could have just quietly close the pull request without any comment if it bothers you so much.

**Comment by jsundra** [comment]
Right, and you could have also quietly ignored my comment, just like you ignored all of the PRs and issues stacking up on this repo.

**Comment by automat** [comment]
Again. Zero obligations. And zero tolerance for your tone. Good luck.

**Pull request closed without merging**
